/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 */

#include <stdint.h>
#include "BSP/stm32f3_discovery_gyroscope.h"

#include "serial.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void){

	srand(time(NULL));  // Seed the random number generator once
	BSP_GYRO_Init();
	float gyro_values[3];


	while (rounds < 5){
		int P1guesses = 0;
		int P2guesses = 0;

		// round of heads up
		while (!timesUp){
			// player 1 plays heads up

			guessWord = randomWord();
			outcome = 0;

			while (!outcome){
				BSP_GYRO_GetXYZ(&gyro_values[0]);
				if (gyro_values[1]/20000 >= 10){
					outcome = 1;
				}
				if (gyro_values[1]/20000 <= -10){
					outcome = 2;
				}
				HAL_Delay(10);
			}

			if (outcome == 1){
				sprintf(string_to_send, "Correct!");
				SerialOutputString(string_to_send, &USART1_PORT);
				P1guesses++;
			}
			else if (outcome == 2){
				sprintf(string_to_send, "Pass!");
				SerialOutputString(string_to_send, &USART1_PORT);
			}
		}
		while (!timesUp){
			// player 2 plays heads up

			guessWord = randomWord();
			outcome = 0;

			while (!outcome){
				BSP_GYRO_GetXYZ(&gyro_values[0]);
				if (gyro_values[1]/20000 >= 10){
					outcome = 1;
				}
				if (gyro_values[1]/20000 <= -10){
					outcome = 2;
				}
				HAL_Delay(10);
			}

			if (outcome == 1){
				sprintf(string_to_send, "Correct!");
				SerialOutputString(string_to_send, &USART1_PORT);
				P2guesses++;
			}
			else if (outcome == 2){
				sprintf(string_to_send, "Pass!");
				SerialOutputString(string_to_send, &USART1_PORT);
			}
		}

		// winner multiplier
		if (P1guesses > P2guesses){
			// player 1 plays wavelength
			multiplier;
			P1guesses = P1guesses * multiplier;
		}
		else if (P2guesses > P1guesses){
			// player 2 plays wavelength
			multiplier;
			P2guesses = P2guesses * multiplier;
		}

		// update leaderboard
		P1leaderboard = P1leaderboard + P1guesses;
		P2leaderboard = P2leaderboard + P2guesses;
	}

	// winner announcement
	// winner spins wheel of fortune

}
